### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-3-evaluacion-intermedia-sararunda#1]
Buen trabajo @sararunda  !

### Algunas pistas para acabarlo:

- [x] Obtén los datos del API con un fetch()
- [x] Usa un `<form>` para cada grupo de `<input>`, incluidos los filtros
- [x] Recuerda asociar con el atributo `htmlFor` en el `<label>` para indicar para qué es cada `<input>`.
- [x] Haz que los `input` del formulario de añadir una nueva frase y de filtrar sean "componentes controlados": deben tener además de la función handler en su evento `onChange`, una variable de estado en su atributo `value`.
- [x] Resetea el estado de tu formulario cuando agregues una frase(limpia los inputs).
- [x] Verifica el filter de personajes, de manera que incluya si la usuaria ha seleccionado todos: https://github.com/Adalab/modulo-3-evaluacion-intermedia-sararunda/blob/54cdee63a4b55c21fccd4a9cf32bcd775a2868be/src/components/App.js#L46 
- [x] Comprueba que los `inputs` tengan algún valor cuando vas a añadir una nueva frase. 
- [x] Revisa los metadatos en `index.html` (`lang`, `title`...)

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by sararunda** [comment]
I think everything is now complete, if you need to know anything, let me know :)

**Comment by ytaylor** [comment]
Good job!
